hyper:
  logging:
    home: ${user.home}/hyper/${hyper.env}/logs
server:
  port: 9999
  servlet:
    context-path: /hyper
spring:
  profiles:
    active: @env@
    include: dao,@env@-dao
  #分页插件会循环依赖
  main:
    allow-circular-references: true
minio:
  endpoint: http://172.18.1.24:9078
  accesskey: geekplus
  secretkey: geekplus
  buckets: heihei1,heihei2
