hyper:
  logging:
    home: ${user.home}/hyper/${hyper.env}/logs
server:
  port: 9999
  servlet:
    context-path: /hyper
spring:
  profiles:
    active: @env@
    include: dao,@env@-dao
  #分页插件会循环依赖
  main:
    allow-circular-references: true
  messages:
    basename: i18n.i18n
minio:
  endpoint: http://127.0.0.1:9078
  accesskey: geekplus
  secretkey: geekplus
  buckets: heihei1,heihei2

#将sql信息打印到控制台
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
